### PR TITLE
Cloud Function - Image Upload Handler

### PR DESCRIPTION
**Pull request by elithrar**
**WORK IN PROGRESS**

This modifies the Function to:

- [x] Handle (only) POST requests from the front-end
- [x] Deal with browser CORS security policies for the browser - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
- [x] Handle image upload as a multipart form
- [x] Validate image size/number of files
- [x] base64 encode the image before upload to the AutoML API
- [x] Submit to the AutoML API for the model

### CODE REVIEW

**Comment by elithrar** [comment]
Don't merge yet, this is just a progress check-in.

**Comment by michelaburns** [comment]
I found a good tutorial for the base64 encode part: https://cloud.google.com/vision/automl/docs/base64

I'll incorporate that in the function!

EDIT: Oh shoot, didn't realize you wanted these additions to the separate wip. I'll change the function back to how it was. Sorry for the confusion

**Review by michelaburns — DISMISSED** [review]
These changes look good! In regards to where the base64-encoding should be, I believe lines 55-68 would be a good spot. Aka, any part that is after we check the file is an image but before the image upload to the AutoML API!

**Comment by elithrar** [comment]
Correct - there does need to be a new event listener inside the
busboy.on(“file”, ...) listener that reads the stream into a buffer first
though.

Having an issue where the listener isn’t firing on the image upload when
testing locally, so need to resolve that today. Node.js makes some simple
things like this more painful.

**Comment by elithrar** [comment]
@michelaburns 

This now works. 

* Handles concatenating chunked (multipart) file uploads into a buffer and base64-encoding
* Returns a `{score: <Number>, label: <String>}` for a given image

You can test locally on the command line by grabbing an image that the model knows the class for and testing:

```
/mnt/c/Users/matt/repos/whats-that-doggo/function (silverlock/function-upload) ✗ 
➜  curl -XPOST "https://us-central1-sp19-codeu-35-7727.cloudfunctions.net/predict" -F file=@malamute.jpg
{"label":"malamute","score":0.8795406818389893}%
```

A class that's not recognized will fail***:

```
➜  curl -XPOST "https://us-central1-sp19-codeu-35-7727.cloudfunctions.net/predict" -F file=@carbon.png
Error: could not handle the request
```

*** _Right now it crashes the Function as the Exception isn't propagated to the `.catch` chain or the outer `try-catch` block - Node.js Exceptions are _not very fun_ at all. Working on fixing that so our error handling is better here, *but this is OK to merge as-is!*_

**Comment by elithrar** [comment]
Fixed in full:

```sh
/mnt/c/Users/matt/Downloads 
➜  curl -XPOST "https://us-central1-sp19-codeu-35-7727.cloudfunctions.net/predict" -F file=@carbon.png
{"error":"Error: Unable to make a prediction for that image: it might be a breed we don't recognize yet!"}%
```

**Comment by michelaburns** [comment]
Hey Matt! Thanks for all of the hard work on this file! In order to get those results from the curl commands you specified, wouldn't I have to have this file? Just in case, I tried running them while cd'd into the function folder

**Command 1**
`curl -XPOST "https://us-central1-sp19-codeu-35-7727.cloudfunctions.net/predict" -F file=@malamute.jpg`

**Response 1**
curl: (26) couldn't open file "malamute.jpg"

**Command 2**
curl -XPOST "https://us-central1-sp19-codeu-35-7727.cloudfunctions.net/predict" -F file=@carbon.png

**Response 2**
curl: (26) couldn't open file "carbon.png"

**Review by michelaburns — APPROVED** [review]
Great job!

**Comment by elithrar** [comment]
Any files will do - it didn’t make sense to include them.

e.g. image search for a dog breed in the label set, and again for any
random image that you would expect to fail.

**Pull request merged**
